name: poets
dependencies:
- cairo=1.12.18=6
- click=6.6=py27_0
- curl=7.45.0=0
- cycler=0.10.0=py27_0
- ecdsa=0.13=py27_0
- flask=0.11.1=py27_0
- fontconfig=2.11.1=5
- freetype=2.5.5=1
- gdal=2.0.0=py27_1
- geos=3.4.2=0
- h5py=2.6.0=np111py27_0
- hdf4=4.2.11=0
- hdf5=1.8.15.1=2
- itsdangerous=0.24=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=0
- kealib=1.4.5=0
- libgdal=2.0.0=2
- libgfortran=3.0.0=1
- libnetcdf=4.3.3.1=3
- libpng=1.6.17=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- netcdf4=1.2.2=np111py27_0
- numpy=1.11.0=py27_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- paramiko=1.16.0=py27_0
- patsy=0.4.1=py27_0
- pillow=3.2.0=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- proj4=4.9.1=0
- py=1.4.31=py27_0
- pycairo=1.10.0=py27_0
- pycrypto=2.6.1=py27_4
- pyparsing=2.1.4=py27_0
- pyproj=1.9.5.1=py27_0
- pyqt=4.11.4=py27_3
- pytest=2.9.2=py27_0
- python=2.7.11=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.4=py27_0
- qt=4.8.7=3
- readline=6.2=2
- requests=2.10.0=py27_0
- scipy=0.17.1=np111py27_0
- setuptools=23.0.0=py27_0
- shapely=1.5.13=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- statsmodels=0.6.1=np111py27_1
- tk=8.5.18=0
- werkzeug=0.11.10=py27_0
- wheel=0.29.0=py27_0
- xerces-c=3.1.2=0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.8
  - babel==2.3.4
  - configobj==5.0.6
  - coverage==4.1
  - docutils==0.12
  - easyprocess==0.2.2
  - flask-cors==2.1.2
  - imagesize==0.7.1
  - patool==1.12
  - pygeobase==0.3.9
  - pygeogrids==0.2.0
  - pygments==2.1.3
  - pykdtree==1.1.1
  - pyresample==1.2.3
  - pyshp==1.2.3
  - pytesmo==0.5.2
  - pytest-cov==2.2.1
  - pyunpack==0.1.1
  - snowballstemmer==1.2.1
  - sphinx==1.4.4
  - sphinx-rtd-theme==0.1.9

